---
title: "03_webscraping_texto_y_fechas"
author: "Caio Moreno"
date: "June 26, 2015"
output: html_document
---

Los ejercicios tienen que resolverse individualmente. No son sencillos: parte de ellos están inspirados en problemas prácticos reales. Por eso puedes ayudarte de cualquier tipo de instrumento (Google, blogs, libros, etc.) que estaría a tu alcance en tu trabajo. Eso sí, en las soluciones que envíes, indica los recursos que utilices y deja clara cuál es tu aportación en cada caso.

El envío de los ficheros se hará por medio del Blackboard. La fecha límite para puntuar sobre 10 es tres semanas después de la clase. A partir de entonces, la nota máxima bajará dos puntos por semana.

A pesar de que hay 14 puntos en juego, las prácticas se evaluarán sobre 10, que es la máxima nota.

### Formato de entrega

El fichero que envíes tiene que contener tres directorios:

1. `dat`, donde almacenarás los datos necesarios y solo los necesarios (piensa que alguno de los ficheros que te pido que uses ocupa muchos megas) para la resolución de los ejercicios. Véanse las excepciones en el enunciado de los ejercicios.
2. `src`, donde estarán los ficheros `.Rmd` y los ficheros `.html` o `.pdf` que generes. Los ficheros tienen que tener un nombre del tipo `01_clases_s4_mapas.Rmd`, `02_json_xml.Rmd` o similar. 

En cada ejercicio se valorará con un 25% de la puntuación final que el fichero `.Rmd` se ejecute y lo haga en un tiempo razonable sin ningún tipo de edición por mi parte.

## Web scraping, texto y fechas (2 puntos)

Descarga información bursátil de `http://goo.gl/yD2Bwb` y crea un `data.frame` a partir de él con la misma información que en la tabla que aparece en la página. Convierte las columnas numéricas a número, etc., las fechas a fecha, etc.

Ten en cuenta que la columna hora puede tener dos tipos de información: la hora durante las horas de operación de los mercados y el día en formato dd/mm/aaaa fuera de mercado. Que tu código tenga en cuenta esa circunstancia.

Alternativamente, si encuentras algunos datos de tu interés que te interese procesar y tengan un nivel de dificulad similar al anterior, úsalos en lugar de los propuestos.

El código que envíes tiene que ser capaz de crear la tabla a la hora en que lo ejecute.


## Web scraping, texto y fechas (2 puntos) - Resolución


```{r}

#Load adminpackage4r
#Info about adminpackage4r package at https://github.com/caiomsouza/adminpackage4r
library("adminpackage4r")

# Specify the list of required packages to be installed and load
Required_Packages=c("stringr", "XML");

# Call the Function
Install_And_Load(Required_Packages);

#library(XML)
#library(stringr)

# IBEX website 
url.ibex <- "http://goo.gl/yD2Bwb"

# Read from IBEX Website 
raw.data <- readLines(url.ibex, warn="F") 
bolsa.doc  <- htmlTreeParse(raw.data, error=function(...){}, useInternalNodes = TRUE,encoding="UTF-8")

#Infos 
class(bolsa.doc)
bolsa.root = xmlRoot(bolsa.doc)
xmlSize(bolsa.root)
xmlSApply(bolsa.root, xmlName)
xmlSApply(bolsa.root, xmlSize)
class(xmlChildren(bolsa.root))
typeof(xmlChildren(bolsa.root))

# Parse IBEX Website
bolsa.body = xmlChildren(bolsa.root)$body
file_header <- xpathSApply(bolsa.body, "//table[@title='Acciones']/*/tr[1]/th", xmlValue)
file_content <- xpathSApply(bolsa.body, "//table[@title='Acciones']/*/tr/td", xmlValue)
file_header <- sapply(file_header, function(x) gsub("^(\n){1,}|(\\*){1,}$", "", x))
bolsa.tabla <- data.frame(matrix(file_content, ncol = 13, byrow = TRUE), stringsAsFactors = FALSE)
bolsa.tabla <- bolsa.tabla[,-5]
file_header<-file_header[-5]
colnames(bolsa.tabla) <- file_header
bolsa.tabla <- bolsa.tabla[order(bolsa.tabla$TKR),]
bolsa.tabla$Último <- as.numeric(gsub(",", ".", bolsa.tabla$Último))
bolsa.tabla$Dif. <- as.numeric(gsub(",", ".", bolsa.tabla$Dif.))
bolsa.tabla$'Dif. %' <- as.numeric(gsub(",", ".", bolsa.tabla$'Dif. %'))
bolsa.tabla$Max. <- as.numeric(gsub(",", ".", bolsa.tabla$Max.))
bolsa.tabla$Min. <- as.numeric(gsub(",", ".", bolsa.tabla$Min.))
bolsa.tabla$Volumen <- as.numeric(gsub("\\.", "", bolsa.tabla$Volumen))
bolsa.tabla$Capital <- as.numeric(gsub("\\.", "", gsub("[:space]*n.d.[:space]*", NA, bolsa.tabla$Capital)))
bolsa.tabla$Último <- as.numeric(gsub(",", ".", bolsa.tabla$Último))
bolsa.tabla$'Rt/Div' <- gsub(",", ".", (gsub("[:space]*n.a.[:space]*", NA, bolsa.tabla$'Rt/Div')))
bolsa.tabla$PER <- as.numeric(gsub(",", ".", gsub("[:space]*n.a.[:space]*", NA, bolsa.tabla$PER)))
bolsa.tabla$BPA <- as.numeric(gsub(",", ".", gsub("[:space]*n.a.[:space]*", NA, bolsa.tabla$BPA)))

#Print 
bolsa.tabla
head(bolsa.tabla, 10)
tail(bolsa.tabla, 10)


```